version: "1.0"
info:
  model: int-scaffold
packages:
- name: Lfx_demo2Project
  gitServerName: https://github.com/debgibm/lfx_demo2
  gitUrl: https://github.com/debgibm/Lfx_demo2Project
  gitUsername: debgibm
  gitBranch: main
services:
- serviceName: project.lfx_demo2.integrations:log_dada
  packages:
  - name: Lfx_demo2Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.927
